name: Deploy JS App to EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  IMAGE_REPO: simple-js-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 0️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3️⃣ Log in to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $ECR_REGISTRY/${{ env.IMAGE_REPO }}:$IMAGE_TAG \
            -t $ECR_REGISTRY/${{ env.IMAGE_REPO }}:latest \
            --push .

      # Step 5️⃣ Terraform Init + Apply
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "image_tag=latest"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_tag=latest"
